Fix migration.
The migration failed on the server with:

django.db.utils.OperationalError: cannot ALTER TABLE "tasks_task"
because it has pending trigger events

See
http://stackoverflow.com/questions/28429933/django-migrations-using-runpython-to-commit-changes
on why this fixes that issue.